# SPDX-License-Identifier: GPL-2.0-only
dtb-$(CONFIG_ARCH_VT8500) += \
	vt8500-bv07.dtb \
	wm8505-ref.dtb \
	wm8650-mid.dtb \
	wm8750-apc8750.dtb \
	wm8850-w70v2.dtb \
	wm8850-twd-pid7-8198-usa.dtb \
	wm8880-hl-pc1088.dtb \
	wm8950-apcrock.dtb \
	wm8950-springboard-vab600.dtb
